### ISSUE TITLE
How can I get the RioBus using ionic 1?

### ISSUE THREAD

**Issue by Warnier-zhang** [RioBus/ionic-app#74]

**Comment by Warnier-zhang** [comment]
I am a newbie...

**Comment by fmsouza** [comment]
This is an Ionic 2 project, you can't run it as Ionic 1. However, if your interest is about using the API to have access to the data, the documentation is in https://github.com/RioBus/proxy/wiki/REST-API.
But, unfortunately, it's in portuguese and does not have any official translation to english.

**Comment by Warnier-zhang** [comment]
Thanks for your reply!
